### ISSUE TITLE
Touchpad issue

### ISSUE THREAD

**Issue by Ricksonk** [Baio1977/Acer-Aspire-A515-54g-CPU-10xxx#1]
Hello! I'm testing your efi in my A515-54. It is the same hardware, but here the touchpad isn't working.  Could you help me?

**Comment by Baio1977** [comment]
[EFI Debug 0.7.5.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7522023/EFI.Debug.0.7.5.zip)

Update the Bios, put the EFI debug in a USB and start at the end of the procedure if you start normally you will find in EFI USB some extracted files attach them here + ioreg and let's see what you can do.
Do you also have windows ???
from the acpi in this reposity, I read 2 models used for that laptop,
You need the acpi of your Bios

![Schermata 2021-11-11 alle 18 13 54](https://user-images.githubusercontent.com/59058746/141340968-e5af755d-25c0-4b67-9fb1-42d459c7eefd.png)

**Comment by Ricksonk** [comment]
[SystemReport.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7530345/SystemReport.zip)

I don't have windows installed. And Bios is already upgraded.

Maybe that is the problem, the trackpad model. I will look for it and take a look at this ACPI too.

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7530427/EFI.zip)
Test this EFI OC0.7.6

**Comment by Ricksonk** [comment]
> [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7530427/EFI.zip) Test this EFI OC0.7.6

from this EFI there is not touchpad and keyboard.  Changing the ACPI, the notebook freezes, but it is saying my touchpad is ELAN0504


OC0.7.3 => here keyboard is working, no touchpad.
OC0.7.6 => No keyboard and no touchpad.

**Comment by Baio1977** [comment]
ioreg OC 0.7.6 describe the precise specifications of your laptop even if it has a discrete GPU as well as integrated

[ACPI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7531542/ACPI.zip)
replace this folder in EFI \ OC and try again

**Comment by Ricksonk** [comment]
[ioreg.txt](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7531938/ioreg.txt)
output of ioreg.


Using this ACPI:
![1636803597787](https://user-images.githubusercontent.com/46610644/141642498-a715eae4-d817-4cbc-b2dc-049da45ec322.jpg)

**Comment by Ricksonk** [comment]
> ioreg OC 0.7.6 describe the precise specifications of your laptop even if it has a discrete GPU as well as integrated
> 
> [ACPI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7531542/ACPI.zip) replace this folder in EFI \ OC and try again


[ioreg.txt](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7531978/ioreg.txt)
Output of ioreg



Using the ACPI
![1636803597787](https://user-images.githubusercontent.com/46610644/141643407-9ed1aa8c-f05a-4f98-85a6-6abaf5d83322.jpg)

**Comment by Baio1977** [comment]
This
[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7532584/EFI.zip)

**Comment by Ricksonk** [comment]
> This [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7532584/EFI.zip)

This EFI works well, keyboard is working but touch not yet.

Checking an EFI from another laptop I found this:
  ### Known Issues
- Trackpad does not work with VoodooI2C kext but works with voodoops2(Place kext in correct order in config.plist)

Could this be the same problem?

**Comment by Baio1977** [comment]
of the efi I pass you I need ioreg, otherwise I'm in the dark

**Comment by fernandoocruz** [comment]
Hello, I have the same issue. My laptop is Acer Aspire A515-54G.
Everything worked fine, but the Wi-Fi (mine is Atheros, so it is expected), keyboard and the touchpad.
My BIOS is updated to the latest version v1.24
I will test the EFI you provided above and check if the problems are solved.

**Comment by Ricksonk** [comment]
> of the efi I pass you I need ioreg, otherwise I'm in the dark

After a factory default reset in the Bios, it is inverse now. Touch works but keyboard don't. 

Using the last EFI you sent me. (touch working)
[ioreg 2.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7534068/ioreg.2.zip)

**Comment by Baio1977** [comment]
I need certainties I would like to know if this EFI works well on Big Sur , ioreg in case save the log
[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7534158/EFI.zip)
Thanks for all
![Schermata 2021-11-14 alle 17 36 13](https://user-images.githubusercontent.com/59058746/141689787-a406a5ee-ff4e-451c-9f33-fdb108ac27d0.png)

**Comment by Ricksonk** [comment]
> I need certainties I would like to know if this EFI works well on Big Sur , ioreg in case save the log [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7534158/EFI.zip) Thanks for all ![Schermata 2021-11-14 alle 17 36 13]

(https://user-images.githubusercontent.com/59058746/141689787-a406a5ee-ff4e-451c-9f33-fdb108ac27d0.png)
[ioreg copy.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7534476/ioreg.copy.zip)

Touch working, but keyboard no.

**Comment by fernandoocruz** [comment]
I can confirm.
Using the last EFI, the touchpad is now working, but the keyboard still not working.

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7536475/EFI.zip)
Test this EFI for the keyboard, if you don't have wi-fi and BT intel remove the respective kext in EFI-OC-Kext and from the config plist section kernel, let us know

**Comment by Ricksonk** [comment]
> [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7536475/EFI.zip) Test this EFI for the keyboard, if you don't have wi-fi and BT intel remove the respective kext in EFI-OC-Kext and from the config plist section kernel, let us know

[ioreg 1511.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7537743/ioreg.15.11.zip)

Keyboard not working yet.

**Comment by fernandoocruz** [comment]
I have the same results here.
Tried the new EFI and removed the Intel kexts on the folder.
Tochpad working fine, but no keyboard.
Thanks for your hard work!

**Comment by Baio1977** [comment]
Try this, I extracted the kext keyboard from VoodooPS2.kext let me know if it works.
Honestly I don't know why the keyboard doesn't work it will be a kernel problem, try to reset nvram to OC's Gui, it's really strange , the order of the kext is right

[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7540588/EFI.zip)

**Comment by Ricksonk** [comment]
> Try this, I extracted the kext keyboard from VoodooPS2.kext let me know if it works. Honestly I don't know why the keyboard doesn't work it will be a kernel problem, try to reset nvram to OC's Gui, it's really strange , the order of the kext is right
> 
> [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7540588/EFI.zip)

I had tried a new installation of Big Sur and still the same issue. Really strange because it works well there for you.

But thanks for all your effort
[ioreg.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7541737/ioreg.zip)
.

**Comment by Baio1977** [comment]
Try replacing VoodooPS2Controller.Kext 2.2.7 with earlier versions, such as 2.2.6 or even earlier
https://github.com/acidanthera/VoodooPS2/releases

**Comment by Ricksonk** [comment]
> Try replacing VoodooPS2Controller.Kext 2.2.7 with earlier versions, such as 2.2.6 or even earlier https://github.com/acidanthera/VoodooPS2/releases

It doesn't work yet. I had tried the same thing with VoodooI2c and VoodooPS2 from OC0.7.3 but nothing has changed...
 I think it is better to give up. I'll be using the last version of your EFI, at least the keyboard is working in this one. 

Thank you for your help

**Comment by Baio1977** [comment]
[EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7560712/EFI.zip)
Test this please

**Comment by Ricksonk** [comment]
> [EFI.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7560712/EFI.zip) Test this please

This error
![1637235929605](https://user-images.githubusercontent.com/46610644/142410155-5ffdec3d-0a70-4cc3-bb79-e13f139b9346.jpg)
