### ISSUE TITLE
Keyboard on A515-54-53VN

### ISSUE THREAD

**Issue by dssilva** [Baio1977/Acer-Aspire-A515-54g-CPU-10xxx#2]
Hi, I have been trying a lot of EFI these days, yours was the best one to my model A515-54-53VN; hdmi output and wake/sleep that was not working in others now is ok. But I still have the same problem from others EFI the laptop keyboard doesn't work at all. Touchpad is perfect with complete gestures, but the keyboard simply doesn't exist.

Could you help with something? I have tried update the VoodooPS2Controller kext on EFI boot, but didn't work. I just need this to have a perfect experience.

**Comment by Italo-Nogueira** [comment]
Any solution? My keyboard too.

**Comment by Baio1977** [comment]
Do you have windows ??
In case I need information the brand of the keyboard device
Test this EFI (https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/releases/tag/V1.1) , ioreg if start , use Kext PS2 and I2C old version .

**Comment by dssilva** [comment]
Hi! The keyboard worked! But now I have another problem, the wifi not. I saw that you are using the Monterey version, here I'm using Big Sur, so I replaced the kext with proper version and changed on plist, but the problem continues. So tried restore the previous  EFI and changed the kexts PS2 and I2C with yours, the keyboard work but the wifi continuous not working.

What can I do?

**Comment by dssilva** [comment]
[ioreg](https://pastebin.com/eAfFJzak)

This is using the new EFI 1.1 that you send with wireless kext from Big Sur.

**Comment by Baio1977** [comment]
Yes, I have seen that the problem arises with the new kext

**Comment by dssilva** [comment]
Any clue for a solution?

**Comment by Baio1977** [comment]
[OC.zip](https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx/files/7699157/OC.zip)
Test this , ioreg if start , save log

![Schermata 2021-12-12 alle 18 00 11](https://user-images.githubusercontent.com/59058746/145721803-dd07ad2f-8b6f-45c9-b014-c71ab1f6a8ca.png)

**Comment by dssilva** [comment]
[https://paste-bin.xyz/23045](https://paste-bin.xyz/23045)

Started.. But still not wifi and now no bluetooth either. I don´t have that app from picture, I´m using a command line tool to export.

**Comment by dssilva** [comment]
![Screen Shot 2021-12-12 at 14 30 02](https://user-images.githubusercontent.com/5356029/145722918-871b6918-81d8-4a46-9c2d-0079643a0ff9.png)

The wifi seems to be starting, but no networks.

**Comment by dssilva** [comment]
Now I can't even go back to how It was before, even using your first version. I'm without keyboard, wi-fi and bluetooth. :( I have already reset nvram.

**Comment by dssilva** [comment]
@Italo-Nogueira teve sucesso usando essa nova versão?

**Comment by dssilva** [comment]
@Baio1977 Hi! So, do you have any idea how I can at least make it work like before? With wifi and bluetooth enabled. Or have any other modification on EFI to try.

**Comment by dssilva** [comment]
@Baio1977 So my problems ended, I was worried that something had happened with the wireless card, so I made a linux bootable and tried it, there everything worked as should be. So to my surprise when I came back to Mac was everything working again. Now I have all working!

**Comment by dssilva** [comment]
Sic... Just one little problem, some keys are regonized wrong, like window key as command and left Alt as option.

**Comment by Baio1977** [comment]
probably the nvram had to be reset, better this way
